### ISSUE TITLE
Can you update nexmon for kernel 6.6.y?

### ISSUE THREAD

**Issue by renewedbullet** [DrSchottky/nexmon#15]
Trying to compile the driver for 6.6.y for RPI 5 and I get this error, I saw on the nexmon repo you updated the firmware previously for 6.2/6.1 

                               presents:

              # ###   ###  #   # # ###  ###   ###  # ###
              ##   # #   #  # #  ##   ##   # #   # ##   #
              #    # #####   #   #    #    # #   # #    #
              #    # #      # #  #    #    # #   # #    #
              #    #  #### #   # #    #    #  ###  #    #

                The C-based Firmware Patching Framework

                           !!! WARNING !!!
    Our software may damage your hardware and may void your hardware’s
     warranty! You use our tools at your own risk and responsibility

  COLLECTING STATISTICS read /home/pi/nexmon/STATISTICS.md for more information
  COMPILING src/version.c => obj/version.o (details: log/compiler.log)
  GENERATING LINKER FILE gen/nexmon.pre => gen/nexmon.ld
  GENERATING LINKER FILE gen/nexmon.pre => gen/flashpatches.ld
  LINKING OBJECTS => gen/patch.elf (details: log/linker.log, log/linker.err)
  GENERATING MAKE FILE gen/nexmon.pre => gen/nexmon.mk
  GENERATING MAKE FILE gen/nexmon.pre => gen/flashpatches.mk
  APPLYING FLASHPATCHES gen/flashpatches.mk => brcmfmac43455-sdio.bin (details: log/flashpatches.log)
  APPLYING PATCHES gen/nexmon.mk => brcmfmac43455-sdio.bin (details: log/patches.log)
Makefile:59: Warning: Driver for kernel 6.6 not found

**Comment by jayofelony** [comment]
Kernel 6.6.20+rpt-rpi-v8 and 6.6.20+rpt-rpi-2712 have been released when you run `apt-get dist-upgrade`.

**Comment by DrSchottky** [comment]
Done
