### ISSUE TITLE
BCM4389 mini request

### ISSUE THREAD

**Issue by TQMatvey** [DrSchottky/nexmon#7]
Hey, looking at all your experience and work, and since as jlinktu said work for bcm4389 is WIP (has been a year bruh...) could you take a try to get nexmon working on bcm4389? 
i can provide remote access to device (S21 Ultra) with root access and everything if you can give a try to get nexmon working...

**Comment by DrSchottky** [comment]
Hi,  unfortunately adding support for a new target requires too much work for a device I don't own (I can't do that on a remote device)
